# Generated by Django 5.2 on 2026-03-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0003_rename_field_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoVeiculoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arquivo', models.CharField(db_index=True, max_length=256)),
                ('Medicao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.medicao')),
                ('Veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.veiculo')),
            ],
        ),
    ]
