# Generated by Django 5.2 on 2026-03-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0004_medicaoveiculotemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='arquivo',
            new_name='arquivoid',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='Medicao',
            new_name='medicaoid',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='Veiculo',
            new_name='veiculoid',
        ),
    ]
