# Generated by Django 5.2 on 2026-03-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0005_rename_arquivo_medicaoveiculotemp_arquivoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='UnidadeMedida',
            new_name='unidade_medida',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='Medicao',
            new_name='medicao',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='Valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='medicaoveiculo',
            old_name='Veiculo',
            new_name='veiculo',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='arquivoid',
            new_name='arquivo_id',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='medicaoid',
            new_name='medicao_id',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='veiculoid',
            new_name='veiculo_id',
        ),
        migrations.RenameField(
            model_name='modelo',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='unidademedida',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Ano',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Horimetro',
            new_name='horimetro',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Modelo',
            new_name='modelo',
        ),
    ]
