# Generated by Django 5.2 on 2026-03-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0006_rename_nome_marca_nome_rename_tipo_medicao_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='arquivo_id',
            new_name='arquivoid',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='medicao_id',
            new_name='medicao_d',
        ),
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='veiculo_id',
            new_name='veiculoid',
        ),
    ]
