# Generated by Django 5.2 on 2026-03-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0007_rename_arquivo_id_medicaoveiculotemp_arquivoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='medicao_d',
            new_name='medicaoid',
        ),
    ]
