# Generated by Django 5.2 on 2026-03-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0008_rename_medicao_d_medicaoveiculotemp_medicaoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='arquivoid',
            new_name='arquivo_id',
        ),
    ]
