# Generated by Django 5.2 on 2026-03-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0009_rename_arquivoid_medicaoveiculotemp_arquivo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaoveiculotemp',
            old_name='arquivo_id',
            new_name='arquivoid',
        ),
    ]
